config/routes.rb
Rails.application.routes.draw do

  resources :ratings
  resources :comments
  resources :likes
  
  root 'static_pages#home'

  get '/posts/:id/rating' => 'posts#rating'
  get '/posts/:id/comments' => 'posts#comment', as: 'post_comments'
  get '/comments/:id/like' => 'comments#likes', as: 'comment_likes'
  get '/home' => 'static_pages#home'

  get '/help' => 'static_pages#help'

  get '/about' => 'static_pages#about'

  get '/contact' => 'static_pages#contact'

  get '/signup' => 'users#new'

  get '/admin' => 'admin#index'

  get '/statuses' => 'statuses#index'
  
  put '/user/new', to: 'users#save', as: :user_save

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do  
    resources :posts do
      resources :chapters
    end
  end
  
  resources :statuses
    

end

app/models/ability.rb
class Ability
  include CanCan::Ability



  def initialize(user)
    user ||= User.new

    if user.has_role?(:admin)
      can :manage, :all
    elsif user.has_role?(:user)
      can :manage, Post, { user_id: user.id }
      can :manage, Chapter
      can :read, :all
      can :show, :all
      can :rating, :all
      can :comment, :all
    else
      can :read, :all
      can :show, :all
      can :rating, :all
      can :comment, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :post
  belongs_to :users

  def show
  end

  def user_id
    self.post.user_id
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  has_many :likes
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :chapters, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy

  def show
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/status.rb
class Status < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable,
                          :trackable, :validatable, :lockable

  has_many :posts, dependent: :destroy
  has_many :comments, through: :posts
  has_many :likes, through: :comments
  before_create :set_default_role

  ROLES = %i[admin user]

  def roles=(roles)
    roles = [*roles].map { |r| r.to_sym }
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+)
  end

  def roles
    ROLES.reject do |r|
      ((roles_mask.to_i || 0) &2**ROLES.index(r)).zero?
    end
  end

  def has_role?(role)
    roles.include?(role)
  end

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }

  private 
  def set_default_role
    self.roles = 'user'
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_action :authenticate_user!

  before_filter :verify_admin

  def index
    @users = User.all
  end

  private
  def verify_admin
    redirect_to root_url unless current_user.has_role?(:admin)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def new
    @like = Like.new
  end

  def create
    @like = Like.find_by(:comment_id => like_params[:comment_id], :user_id => like_params[:user_id])
    if @like
      @like.destroy
    else
      @like = Like.new(like_params)
      @like.save
    end

    respond_to do |format|
      if @like.save
        format.html { redirect_to '#', notice: 'like was successfully created.' }
        format.json { render :show, status: :created, location: @like }
      else
        format.html { render :new }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end    
  end

  private
    def like_params
      params.require(:like).permit(:comment_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action only: [:show, :edit, :update, :destroy, :save]


  def new
    @post = Post.new(:user_id => params[:user_id])
    authorize! :manage, @post
  end

  def post_params
    params.require(:post).permit(:title)
  end

  def show
    @post = Post.find_by(:id => params[:id])
  end

  def edit
  end

  def save
  end

  def create
    @user = User.find_by(:id => params[:user_id])
    @post = @user.posts.create(post_params)
    @post.chapters.create(:number => 1, :title => 'First chapter')
    redirect_to edit_user_post_path(:id => @post.id)
  end

  def rating
    @post = Post.find_by(:id => params[:id])
    if @post.ratings.average(:stars)
      @stars = @post.ratings.average(:stars).round(1)
    else
      @stars = '-'
    end

    if current_user
      if(@rating = @post.ratings.find_by(:user_id => current_user.id))
        render :json => {:user_stars => @rating.stars, :stars => @stars}
      else
        render :json => {:stars => @stars}
      end 
    else
      render :json => {:stars => @stars}
    end 
  end
  
  def update
  end

  def comment
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_url(:id => params[:user_id]), notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "iTexts"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="alert alert-danger">
      <h2 class="text-danger">#{sentence}</h2>
      <ul class="text-danger text-left">#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {})
    size = options[:size] || '80px';
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/index.html.erb
<% provide(:title, 'Admin') %>

<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<%= link_to 'New User', new_user_path %>

app/views/layouts/_footer.html.erb
<footer class="footer center col-md-offset-2 col-md-8">
  <small>
    The <a href="#">site</a> for authors and
              readers by <a href="#">Roman Pavlov</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <nav class="navbar navbar-default navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "iTexts", root_path, class: "navbar-brand logo" %>
      </div> <!-- End div "navbar-header" -->

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <!--<form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>-->
        <ul class="nav navbar-nav pull-right">
          <%= render 'layouts/header/navigation' %>        
          <%= render 'layouts/header/user_menu' %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <%= value %>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/layouts/header/_navigation.html.erb
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                            aria-haspopup="true" aria-expanded="false">
                            Navigation <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><%= link_to "Home",   root_path %></li>
    <li><%= link_to "Help",   help_path %></li>
  </ul>
</li> 

app/views/layouts/header/_user_menu.html.erb
<% if user_signed_in? %>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
      <%= current_user.name %>
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to 'Profile', user_path(current_user.id) %></li>
      <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
    </ul>
  </li>
<% else %>
  <li><%= link_to 'Log In', new_user_session_path %></li>
  <li><%= link_to 'Sign Up', new_user_registration_path %></li>
<% end %>

app/views/ratings_bak/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :stars %><br>
    <%= f.number_field :stars %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings_bak/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings_bak/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>User</th>
      <th>Stars</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.post %></td>
        <td><%= rating.user %></td>
        <td><%= rating.stars %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings_bak/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings_bak/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @rating.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @rating.user %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @rating.stars %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>