config/routes.rb
Rails.application.routes.draw do

  resources :ratings
  resources :comments
  resources :likes
  
  root 'static_pages#home'

  get '/posts/:id/rating' => 'posts#rating'
  get '/posts/:id/comments' => 'posts#comment', as: 'post_comments'
  get '/comments/:id/like' => 'comments#likes', as: 'comment_likes'
  get '/home' => 'static_pages#home'

  get '/help' => 'static_pages#help'

  get '/about' => 'static_pages#about'

  get '/contact' => 'static_pages#contact'

  get '/signup' => 'users#new'

  get '/admin' => 'admin#index'

  get '/statuses' => 'statuses#index'
  
  put '/user/new', to: 'users#save', as: :user_save

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :users do  
    resources :posts do
      resources :chapters
    end
  end
  
  resources :statuses
    

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :chapters, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy

  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action only: [:show, :edit, :update, :destroy, :save]


  def new
    @post = Post.new(:user_id => params[:user_id])
    authorize! :manage, @post
  end

  def post_params
    params.require(:post).permit(:title)
  end

  def show
    @post = Post.find_by(:id => params[:id])
  end

  def edit
  end

  def save
  end

  def create
    @user = User.find_by(:id => params[:user_id])
    @post = @user.posts.create(post_params)
    @post.chapters.create(:number => 1, :title => 'First chapter')
    redirect_to edit_user_post_path(:id => @post.id)
  end

  def rating
    @post = Post.find_by(:id => params[:id])
    if @post.ratings.average(:stars)
      @stars = @post.ratings.average(:stars).round(1)
    else
      @stars = '-'
    end

    if current_user
      if(@rating = @post.ratings.find_by(:user_id => current_user.id))
        render :json => {:user_stars => @rating.stars, :stars => @stars}
      else
        render :json => {:stars => @stars}
      end 
    else
      render :json => {:stars => @stars}
    end 
  end
  
  def update
  end

  def comment
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to user_url(:id => params[:user_id]), notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/views/posts/_comment.html.erb
<div class="comment-header row">
  <div class="col-xs-8 col-sm-10 pull-left">
    <%= link_to gravatar_for(comment.user, {:size => '24'}), user_path(:id => comment.user.id), class: "post-author" %>
    <%= link_to comment.user.name, user_path(:id => comment.user.id), class: "post-author" %>
  </div>
  <div class="col-xs-4 col-sm-2 comment-btns pull-right">
            <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe,
                  comment_path(:id => comment.id), :data => {:confirm => 'Are you sure?'}, :method => 'delete' %>
  </div>
</div>
<div class="comment-body">
  <%= comment.text %>
</div>
<div class="comment-footer">
  <div class="comment-datetime pull-left"><%= comment.created_at %></div>
  <%= render :partial => 'likes', :locals => {:comment => comment} %>
</div>

app/views/posts/_footer.html.erb
<% form_id = "post_#{post.id}_rating" %>
<div class="post-footer">
  <ul>
    <li><span id='<%= "#{form_id}_number" %>'></span></li>
    <li>
      <%= form_for post.ratings.build,
                      :html => {:id => form_id, :class => 'rating-form', data: {ajax_path: "/posts/#{post.id}/rating"}} do |f| %>
        <%= f.hidden_field :post_id %>
        <% if current_user %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
        <% end %>
        <%= f.hidden_field :stars, :id => "#{form_id}_stars" %>
      <% end %>
      <% (1..5).each do |i| %>
        <span class="glyphicon glyphicon-star-empty star-rating" id='<%= "#{form_id}_#{i}" %>' data-stars="<%= i %>" data-form-id="<%= form_id %>"></span>
      <% end %>
    </li>

    <li>
      <%= link_to gravatar_for(post.user, {:size => '24'}), user_path(:id => post.user.id), class: "post-author" %>
      <%= link_to post.user.name, user_path(:id => post.user.id), class: "post-author" %>
    </li>

    <li>
      <% if post.comments.length != 0 %>
        <%= link_to '<span class="glyphicon glyphicon-comment"></span>'.html_safe, post_comments_path(:id => post.id) %>
        <%= post.comments.length %>
      <% else %>
        <%= link_to 'Comment', post_comments_path(:id => post.id) %>
      <% end %>
    </li>
  </ul>
</div>

app/views/posts/_form.html.erb
<div class="center">
  <div class="row">
    <%= form_for(@post, :url => user_posts_path,
            html: { method: :post, class: 'col-md-offset-4 col-md-4' }) do |f| %>

      <div class="form-group">
        <%= f.label :title %><br/>
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= f.submit "Create", class: 'btn btn-primary'  %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_likes.html.erb
<% form_id = "comment_#{comment.id}_likes" %>
<ul class="pull-right">
  <li><span id='<%= "#{form_id}_number" %>'></span></li>
  <li>
    <%= form_for comment.likes.build, :html => {:id => form_id, :class => 'likes-form',
                    data: {ajax_path: "/comments/#{comment.id}/like"}} do |f| %>
      <%= f.hidden_field :comment_id %>
      <% if current_user %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
      <% end %>
    <% end %>
    <span class="glyphicon glyphicon-heart likes" data-form-id="<%= form_id %>" id="<%= "#{form_id}_icon" %>"></span>
  </li>
</ul>

app/views/posts/_post.html.erb
<div class="row my-article">
  <article class="center col-md-offset-2 col-md-8">
    <header class="row">
      <div class="col-xs-8 col-sm-10">
        <h1 class="post-title"><%= post.title %></h1>
      </div>

      <% if current_user && @show_buttons %>
        <% if current_user.id == @user.id || User.find_by(:id => current_user.id).has_role?(:admin) %>
          <div class="col-xs-4 col-sm-2 post-btns">

            <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe,
                  edit_user_post_path(:user_id => @user.id, :id => post.id) %>
            <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe,
                  user_post_path(:user_id => @user.id, :id => post.id),
                  :data => {:confirm => 'Are you sure?'}, :method => 'delete' %>
          </div>
        <% end %>
      <% end %>
    </header>

    <div class="post-preview-content"> 
      <% @chapter = post.chapters.find_by(:number => 1) %>
      <h4><%= @chapter.title %></h4>
      <% if @chapter.content %>
        <p><%= (@chapter.content.split[0..100].join(' ')) + ' ' %><%= link_to 'read more',
                      user_post_chapter_path(:id => @chapter.id, :post_id => post.id, :user_id => post.user.id) %></p>
      <% else %>
        <p>No content yet</p>
      <% end %>
    </div>
    <footer>
      <%= render partial: 'posts/footer', locals: {post: post} %>
    </footer>
  </article>
</div>

app/views/posts/comment.html.erb
<%= render partial: '/posts/post', locals: {:post => @post} %>

    <% @post.comments.each do |comment| %>
      <div class="row">
        <div class="col-md-offset-2 col-md-8">
          <%= render partial: 'comment', locals: {:comment => comment} %>
        </div>
      </div>
    <% end %>

<div class="row">
  <div class="col-md-offset-2 col-md-8 comment-login">

    <% if current_user %>
      <%= form_for(@post.comments.build) do |f| %>
        <%= f.hidden_field :post_id, :value => @post.id %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <div class="form-group">
          <%= f.label :text %><br>
          <%= f.text_area :text, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    <% else %>
      <h2>You have to <%= link_to 'Log In', new_user_session_path %> or 
                            <%= link_to 'Sign Up', new_user_registration_path %>
                            to leave comments!</h2>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, 'Edit post') %>
<h1>Edit <%= @post.title %></h1>
<% @post.chapters.each do |chapter| %>
  <div class="chapter-preview">
    <div class="row">
      <div class="center col-md-offset-2 col-md-8">
        <div class="col-xs-8 col-sm-10">
          <h2><%= chapter.title %></h2>
        </div>
      </div>  
      <div class="col-xs-4 col-sm-2 post-btns">
          <%= link_to '<span class="glyphicon glyphicon-remove"></span>'.html_safe,
                     user_post_chapter_path(:post_id => @post.id, :id => chapter.id),
                     :data => {:confirm => 'Are you sure?'}, :method => :delete %>
          <%= link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe,
                     edit_user_post_chapter_path(:post_id => @post.id, :id => chapter.id) %>
      </div>  
    </div>
    <div class="row">
      <div class="center col-md-offset-2 col-md-8">
        <% if chapter.content %>
          <p><%= (chapter.content.split[0..100].join(' ')) + ' ' %></p>
        <% else %>
          <p>No content yet</p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-offset-2">
    <%= link_to 'New chapter', new_user_post_chapter_path(:post_id => @post.id), :class => "btn btn-primary btn-left" %>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:title, 'New post') %>
<h1>Post creator</h1>
  <%= render 'form' %>


<%= link_to 'Back', user_path(:id => params[:user_id]) %>

app/views/posts/show.html.erb
<div class="chapter-list">
  <% @post.chapters.each do |chapter| %>
    <div class="row">
      <div class="col-md-offset-2 col-md-8 chapter-title">
        <% if !chapter.title.blank? %>
          <%= link_to chapter.title, user_post_chapter_path(:id => chapter.id, :user_id => chapter.user_id, :post_id => chapter.post_id) %>
        <% else %>
          <%= link_to chapter.number, user_post_chapter_path(:id => chapter.id, :user_id => chapter.user_id, :post_id => chapter.post_id) %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <% if chapter.content %>
          <p><%= (chapter.content.split[0..100].join(' ')) + ' ' %><%= link_to 'read more',
                        user_post_chapter_path(:id => chapter.id, :post_id => chapter.post.id, :user_id => chapter.post.user.id) %></p>
        <% else %>
          <p>No content yet</p>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-2 col-md-8 chapter-title">
        <%= link_to "Back to #{@post.user.name}", user_path(:id => @post.user.id) %>
      </div>
    </div>
  <% end %>
</div>